"""initial schema

Revision ID: 88a4e63a93c0
Revises:
Create Date: 2026-08-28 12:09:29.871832

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "88a4e63a93c0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brands")),
        sa.UniqueConstraint("name", name="uq_brand_name"),
    )
    op.create_index(op.f("ix_brands_id"), "brands", ["id"], unique=False)
    op.create_index(op.f("ix_brands_name"), "brands", ["name"], unique=False)
    op.create_table(
        "companies",
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=True),
        sa.Column("trading_name", sa.String(length=255), nullable=True),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("normalized_domain", sa.String(length=255), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("region", sa.String(length=150), nullable=True),
        sa.Column("city", sa.String(length=150), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("postal_code", sa.String(length=50), nullable=True),
        sa.Column("industry", sa.String(length=150), nullable=True),
        sa.Column("company_type", postgresql.ARRAY(sa.String(length=50)), nullable=True),
        sa.Column("business_model", sa.String(length=255), nullable=True),
        sa.Column("founded_year", sa.Integer(), nullable=True),
        sa.Column("employee_range", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("main_products_summary", sa.Text(), nullable=True),
        sa.Column("target_markets", postgresql.ARRAY(sa.String(length=100)), nullable=True),
        sa.Column("manufacturer", sa.Boolean(), nullable=False),
        sa.Column("importer", sa.Boolean(), nullable=False),
        sa.Column("distributor", sa.Boolean(), nullable=False),
        sa.Column("wholesaler", sa.Boolean(), nullable=False),
        sa.Column("retailer", sa.Boolean(), nullable=False),
        sa.Column("ecommerce", sa.Boolean(), nullable=False),
        sa.Column("rental", sa.Boolean(), nullable=False),
        sa.Column("oem", sa.Boolean(), nullable=False),
        sa.Column(
            "company_status",
            sa.Enum("ACTIVE", "INACTIVE", "SUSPENDED", "OTHER", "UNKNOWN", name="companystatus"),
            nullable=False,
        ),
        sa.Column(
            "research_status",
            sa.Enum(
                "NEW",
                "DISCOVERED",
                "COMPANY_RESEARCHED",
                "PRODUCT_RESEARCHED",
                "CONTACT_RESEARCHED",
                "CONTACT_VERIFIED",
                "SOCIAL_RESEARCHED",
                "WHATSAPP_RESEARCHED",
                "FULLY_ENRICHED",
                "NEEDS_RESEARCH",
                "RESEARCH_FAILED",
                name="researchstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "research_level",
            sa.Enum("L0", "L1", "L2", "L3", "L4", "L5", "L6", "L7", "L8", name="researchlevel"),
            nullable=False,
        ),
        sa.Column("company_score", sa.Float(), nullable=True),
        sa.Column("lead_score", sa.Float(), nullable=True),
        sa.Column("ai_context", sa.Text(), nullable=True),
        sa.Column("last_researched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_research_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
    )
    op.create_index(op.f("ix_companies_company_name"), "companies", ["company_name"], unique=False)
    op.create_index(op.f("ix_companies_country_code"), "companies", ["country_code"], unique=False)
    op.create_index(op.f("ix_companies_id"), "companies", ["id"], unique=False)
    op.create_index(op.f("ix_companies_lead_score"), "companies", ["lead_score"], unique=False)
    op.create_index(
        op.f("ix_companies_normalized_domain"), "companies", ["normalized_domain"], unique=True
    )
    op.create_index(
        op.f("ix_companies_research_status"), "companies", ["research_status"], unique=False
    )
    op.create_table(
        "products",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "SUP",
                "INFLATABLE_SUP",
                "HARD_SUP",
                "TOURING_SUP",
                "ALL_ROUND_SUP",
                "RACE_SUP",
                "YOGA_SUP",
                "KAYAK",
                "INFLATABLE_KAYAK",
                "FISHING_KAYAK",
                "TOURING_KAYAK",
                "INFLATABLE_BOAT",
                "RIB",
                "PADDLE",
                "PUMP",
                "LIFE_JACKET",
                "WATER_TOY",
                "ACCESSORY",
                "OTHER",
                name="productcategory",
            ),
            nullable=True,
        ),
        sa.Column("subcategory", sa.String(length=150), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("name", name="uq_product_name"),
    )
    op.create_index(op.f("ix_products_category"), "products", ["category"], unique=False)
    op.create_index(op.f("ix_products_id"), "products", ["id"], unique=False)
    op.create_index(op.f("ix_products_name"), "products", ["name"], unique=False)
    op.create_table(
        "contacts",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sa.String(length=150), nullable=True),
        sa.Column("last_name", sa.String(length=150), nullable=True),
        sa.Column("full_name", sa.String(length=300), nullable=False),
        sa.Column("job_title", sa.String(length=255), nullable=True),
        sa.Column("department", sa.String(length=150), nullable=True),
        sa.Column(
            "seniority",
            sa.Enum("EXECUTIVE", "SENIOR", "MID", "JUNIOR", "UNKNOWN", name="seniority"),
            nullable=True,
        ),
        sa.Column(
            "role_type",
            sa.Enum(
                "OWNER",
                "FOUNDER",
                "CEO",
                "GENERAL_MANAGER",
                "PURCHASING_MANAGER",
                "BUYER",
                "PROCUREMENT",
                "PRODUCT_MANAGER",
                "IMPORT_MANAGER",
                "SALES_DIRECTOR",
                "MARKETING_DIRECTOR",
                "EXECUTIVE",
                "OTHER",
                "UNKNOWN",
                name="roletype",
            ),
            nullable=True,
        ),
        sa.Column(
            "purchasing_role",
            sa.Enum(
                "DECISION_MAKER",
                "BUYER",
                "INFLUENCER",
                "TECHNICAL",
                "EXECUTIVE",
                "SALES",
                "MARKETING",
                "UNKNOWN",
                name="purchasingrole",
            ),
            nullable=True,
        ),
        sa.Column(
            "decision_power",
            sa.Enum("HIGH", "MEDIUM", "LOW", "UNKNOWN", name="decisionpower"),
            nullable=True,
        ),
        sa.Column("linkedin_url", sa.String(length=500), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "LEFT_COMPANY", "UNKNOWN", name="contactstatus"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_contacts_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contacts")),
    )
    op.create_index(op.f("ix_contacts_company_id"), "contacts", ["company_id"], unique=False)
    op.create_index(op.f("ix_contacts_full_name"), "contacts", ["full_name"], unique=False)
    op.create_index(op.f("ix_contacts_id"), "contacts", ["id"], unique=False)
    op.create_index(
        op.f("ix_contacts_purchasing_role"), "contacts", ["purchasing_role"], unique=False
    )
    op.create_table(
        "lead_scores",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("product_fit", sa.Float(), nullable=False),
        sa.Column("company_fit", sa.Float(), nullable=False),
        sa.Column("market_fit", sa.Float(), nullable=False),
        sa.Column("purchasing_potential", sa.Float(), nullable=False),
        sa.Column("contact_quality", sa.Float(), nullable=False),
        sa.Column("growth_signals", sa.Float(), nullable=False),
        sa.Column("data_completeness", sa.Float(), nullable=False),
        sa.Column("recent_activity", sa.Float(), nullable=False),
        sa.Column("total_score", sa.Float(), nullable=False),
        sa.Column("grade", sa.String(length=4), nullable=True),
        sa.Column("breakdown", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_lead_scores_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_scores")),
        sa.UniqueConstraint("company_id", name=op.f("uq_lead_scores_company_id")),
    )
    op.create_index(op.f("ix_lead_scores_id"), "lead_scores", ["id"], unique=False)
    op.create_table(
        "research_tasks",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "task_type",
            sa.Enum(
                "COMPANY_DISCOVERY",
                "COMPANY_RESEARCH",
                "PRODUCT_RESEARCH",
                "BRAND_RESEARCH",
                "CONTACT_DISCOVERY",
                "EMAIL_DISCOVERY",
                "PHONE_DISCOVERY",
                "WHATSAPP_DISCOVERY",
                "SOCIAL_DISCOVERY",
                "VERIFICATION",
                "BUYING_SIGNAL_RESEARCH",
                "LEAD_SCORING",
                "FULL_ENRICHMENT",
                name="tasktype",
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "RUNNING", "COMPLETED", "FAILED", "RETRY", "CANCELLED", name="taskstatus"
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "scheduled_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("worker_id", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("result_summary", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_research_tasks_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_tasks")),
    )
    op.create_index(
        "ix_research_claim",
        "research_tasks",
        ["status", "priority", "scheduled_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('PENDING', 'RETRY')"),
    )
    op.create_index(
        op.f("ix_research_tasks_company_id"), "research_tasks", ["company_id"], unique=False
    )
    op.create_index(op.f("ix_research_tasks_id"), "research_tasks", ["id"], unique=False)
    op.create_index(op.f("ix_research_tasks_status"), "research_tasks", ["status"], unique=False)
    op.create_table(
        "research_evidence",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column("field_name", sa.String(length=150), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("source_domain", sa.String(length=255), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum(
                "OFFICIAL_WEBSITE",
                "OFFICIAL_CONTACT_PAGE",
                "OFFICIAL_TEAM_PAGE",
                "OFFICIAL_PRODUCT_PAGE",
                "OFFICIAL_CATALOG",
                "OFFICIAL_SOCIAL",
                "LINKEDIN",
                "INDUSTRY_DIRECTORY",
                "TRADE_PUBLICATION",
                "SEARCH_RESULT",
                "IMPORTED_DATA",
                "OTHER",
                name="sourcetype",
            ),
            nullable=False,
        ),
        sa.Column("evidence_text", sa.Text(), nullable=True),
        sa.Column("extraction_method", sa.String(length=100), nullable=True),
        sa.Column(
            "confidence",
            sa.Enum("HIGH", "MEDIUM", "LOW", "UNKNOWN", name="evidenceconfidence"),
            nullable=False,
        ),
        sa.Column(
            "discovered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_research_evidence_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_research_evidence_contact_id_contacts"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_evidence")),
        sa.UniqueConstraint("content_hash", name="uq_evidence_hash"),
    )
    op.create_index(
        op.f("ix_research_evidence_company_id"), "research_evidence", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_research_evidence_contact_id"), "research_evidence", ["contact_id"], unique=False
    )
    op.create_index(
        op.f("ix_research_evidence_content_hash"),
        "research_evidence",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_evidence_field_name"), "research_evidence", ["field_name"], unique=False
    )
    op.create_index(op.f("ix_research_evidence_id"), "research_evidence", ["id"], unique=False)
    op.create_index(
        op.f("ix_research_evidence_source_domain"),
        "research_evidence",
        ["source_domain"],
        unique=False,
    )
    op.create_table(
        "company_brands",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("brand_id", sa.Uuid(), nullable=False),
        sa.Column(
            "relationship_type",
            sa.Enum(
                "OWNED",
                "DISTRIBUTOR",
                "IMPORTER",
                "DEALER",
                "RESELLER",
                "COMPETITOR",
                "PARTNER",
                "OTHER",
                name="brandrelationship",
            ),
            nullable=False,
        ),
        sa.Column("source_evidence_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_company_brands_brand_id_brands"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_company_brands_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_evidence_id"],
            ["research_evidence.id"],
            name=op.f("fk_company_brands_source_evidence_id_research_evidence"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_brands")),
        sa.UniqueConstraint(
            "company_id", "brand_id", "relationship_type", name="uq_company_brand_rel"
        ),
    )
    op.create_index(
        op.f("ix_company_brands_brand_id"), "company_brands", ["brand_id"], unique=False
    )
    op.create_index(
        op.f("ix_company_brands_company_id"), "company_brands", ["company_id"], unique=False
    )
    op.create_index(op.f("ix_company_brands_id"), "company_brands", ["id"], unique=False)
    op.create_table(
        "company_events",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "NEW_PRODUCT",
                "NEW_BRAND",
                "NEW_DISTRIBUTOR",
                "NEW_HIRING",
                "NEW_MANAGER",
                "NEW_STORE",
                "EXPANSION",
                "NEW_WAREHOUSE",
                "TRADE_SHOW",
                "CATALOG_RELEASE",
                "WEBSITE_UPDATE",
                "PARTNERSHIP",
                "PRODUCT_CATEGORY_EXPANSION",
                "OTHER",
                name="eventtype",
            ),
            nullable=False,
        ),
        sa.Column("event_date", sa.Date(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "importance",
            sa.Enum("CRITICAL", "HIGH", "MEDIUM", "LOW", name="importance"),
            nullable=False,
        ),
        sa.Column("source_evidence_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_company_events_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_evidence_id"],
            ["research_evidence.id"],
            name=op.f("fk_company_events_source_evidence_id_research_evidence"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_events")),
    )
    op.create_index(
        op.f("ix_company_events_company_id"), "company_events", ["company_id"], unique=False
    )
    op.create_index(op.f("ix_company_events_id"), "company_events", ["id"], unique=False)
    op.create_table(
        "contact_methods",
        sa.Column("contact_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "method_type",
            sa.Enum(
                "EMAIL",
                "PHONE",
                "MOBILE",
                "WHATSAPP",
                "TELEGRAM",
                "SKYPE",
                "OTHER",
                name="methodtype",
            ),
            nullable=False,
        ),
        sa.Column("value", sa.String(length=500), nullable=False),
        sa.Column("normalized_value", sa.String(length=500), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("is_business", sa.Boolean(), nullable=False),
        sa.Column(
            "public_or_private",
            sa.Enum("PUBLIC", "PRIVATE", "UNKNOWN", name="privacylabel"),
            nullable=False,
        ),
        sa.Column(
            "verification_status",
            sa.Enum("UNVERIFIED", "VERIFIED", "INFERRED", "CONFLICTING", name="verificationstatus"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("source_evidence_id", sa.Uuid(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_contact_methods_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_contact_methods_contact_id_contacts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_evidence_id"],
            ["research_evidence.id"],
            name=op.f("fk_contact_methods_source_evidence_id_research_evidence"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_methods")),
        sa.UniqueConstraint(
            "contact_id", "method_type", "normalized_value", name="uq_contact_method_value"
        ),
    )
    op.create_index(
        op.f("ix_contact_methods_company_id"), "contact_methods", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_contact_methods_contact_id"), "contact_methods", ["contact_id"], unique=False
    )
    op.create_index(op.f("ix_contact_methods_id"), "contact_methods", ["id"], unique=False)
    op.create_table(
        "social_accounts",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column(
            "platform",
            sa.Enum(
                "LINKEDIN",
                "INSTAGRAM",
                "FACEBOOK",
                "YOUTUBE",
                "TIKTOK",
                "PINTEREST",
                "X",
                "WHATSAPP",
                "TELEGRAM",
                "OTHER",
                name="platform",
            ),
            nullable=False,
        ),
        sa.Column("profile_url", sa.String(length=500), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column(
            "business_or_personal",
            sa.Enum("BUSINESS", "PERSONAL", "UNKNOWN", name="businessorpersonal"),
            nullable=False,
        ),
        sa.Column("followers", sa.Integer(), nullable=True),
        sa.Column(
            "activity_level",
            sa.Enum("VERY_HIGH", "HIGH", "MEDIUM", "LOW", "NONE", "UNKNOWN", name="activitylevel"),
            nullable=False,
        ),
        sa.Column(
            "verification_status",
            sa.Enum("UNVERIFIED", "VERIFIED", "INFERRED", "CONFLICTING", name="verificationstatus"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("source_evidence_id", sa.Uuid(), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_social_accounts_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_social_accounts_contact_id_contacts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_evidence_id"],
            ["research_evidence.id"],
            name=op.f("fk_social_accounts_source_evidence_id_research_evidence"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_social_accounts")),
        sa.UniqueConstraint("company_id", "platform", "profile_url", name="uq_social_profile"),
    )
    op.create_index(
        op.f("ix_social_accounts_company_id"), "social_accounts", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_social_accounts_contact_id"), "social_accounts", ["contact_id"], unique=False
    )
    op.create_index(op.f("ix_social_accounts_id"), "social_accounts", ["id"], unique=False)
    op.create_index(
        op.f("ix_social_accounts_platform"), "social_accounts", ["platform"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_social_accounts_platform"), table_name="social_accounts")
    op.drop_index(op.f("ix_social_accounts_id"), table_name="social_accounts")
    op.drop_index(op.f("ix_social_accounts_contact_id"), table_name="social_accounts")
    op.drop_index(op.f("ix_social_accounts_company_id"), table_name="social_accounts")
    op.drop_table("social_accounts")
    op.drop_index(op.f("ix_contact_methods_id"), table_name="contact_methods")
    op.drop_index(op.f("ix_contact_methods_contact_id"), table_name="contact_methods")
    op.drop_index(op.f("ix_contact_methods_company_id"), table_name="contact_methods")
    op.drop_table("contact_methods")
    op.drop_index(op.f("ix_company_events_id"), table_name="company_events")
    op.drop_index(op.f("ix_company_events_company_id"), table_name="company_events")
    op.drop_table("company_events")
    op.drop_index(op.f("ix_company_brands_id"), table_name="company_brands")
    op.drop_index(op.f("ix_company_brands_company_id"), table_name="company_brands")
    op.drop_index(op.f("ix_company_brands_brand_id"), table_name="company_brands")
    op.drop_table("company_brands")
    op.drop_index(op.f("ix_research_evidence_source_domain"), table_name="research_evidence")
    op.drop_index(op.f("ix_research_evidence_id"), table_name="research_evidence")
    op.drop_index(op.f("ix_research_evidence_field_name"), table_name="research_evidence")
    op.drop_index(op.f("ix_research_evidence_content_hash"), table_name="research_evidence")
    op.drop_index(op.f("ix_research_evidence_contact_id"), table_name="research_evidence")
    op.drop_index(op.f("ix_research_evidence_company_id"), table_name="research_evidence")
    op.drop_table("research_evidence")
    op.drop_index(op.f("ix_research_tasks_status"), table_name="research_tasks")
    op.drop_index(op.f("ix_research_tasks_id"), table_name="research_tasks")
    op.drop_index(op.f("ix_research_tasks_company_id"), table_name="research_tasks")
    op.drop_index(
        "ix_research_claim",
        table_name="research_tasks",
        postgresql_where=sa.text("status IN ('PENDING', 'RETRY')"),
    )
    op.drop_table("research_tasks")
    op.drop_index(op.f("ix_lead_scores_id"), table_name="lead_scores")
    op.drop_table("lead_scores")
    op.drop_index(op.f("ix_contacts_purchasing_role"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_full_name"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_company_id"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_index(op.f("ix_products_name"), table_name="products")
    op.drop_index(op.f("ix_products_id"), table_name="products")
    op.drop_index(op.f("ix_products_category"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_companies_research_status"), table_name="companies")
    op.drop_index(op.f("ix_companies_normalized_domain"), table_name="companies")
    op.drop_index(op.f("ix_companies_lead_score"), table_name="companies")
    op.drop_index(op.f("ix_companies_id"), table_name="companies")
    op.drop_index(op.f("ix_companies_country_code"), table_name="companies")
    op.drop_index(op.f("ix_companies_company_name"), table_name="companies")
    op.drop_table("companies")
    op.drop_index(op.f("ix_brands_name"), table_name="brands")
    op.drop_index(op.f("ix_brands_id"), table_name="brands")
    op.drop_table("brands")
    # ### end Alembic commands ###
    _drop_enums()


def _drop_enums() -> None:
    """Drop PG enum types explicitly so a later `upgrade head` is repeatable."""
    from sqlalchemy.dialects import postgresql

    for name in [
        "activitylevel",
        "brandrelationship",
        "businessorpersonal",
        "companystatus",
        "contactstatus",
        "decisionpower",
        "eventtype",
        "evidenceconfidence",
        "importance",
        "methodtype",
        "platform",
        "privacylabel",
        "productcategory",
        "purchasingrole",
        "researchlevel",
        "researchstatus",
        "roletype",
        "seniority",
        "sourcetype",
        "taskstatus",
        "tasktype",
        "verificationstatus",
    ]:
        postgresql.ENUM(name=name).drop(bind=op.get_bind(), checkfirst=True)
