"""add ai contexts

Revision ID: 92a389f336cf
Revises: 88a4e63a93c0
Create Date: 2026-08-28 13:54:28.117710

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "92a389f336cf"
down_revision: str | Sequence[str] | None = "88a4e63a93c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_contexts",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("context_type", sa.String(length=40), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "regenerated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_ai_contexts_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_ai_contexts_contact_id_contacts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_contexts")),
        sa.UniqueConstraint("company_id", "context_type", "contact_id", name="uq_ai_context_scope"),
    )
    op.create_index(op.f("ix_ai_contexts_company_id"), "ai_contexts", ["company_id"], unique=False)
    op.create_index(op.f("ix_ai_contexts_id"), "ai_contexts", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ai_contexts_id"), table_name="ai_contexts")
    op.drop_index(op.f("ix_ai_contexts_company_id"), table_name="ai_contexts")
    op.drop_table("ai_contexts")
    # ### end Alembic commands ###
