from __future__ import annotations

from enum import StrEnum


class CompanyType(StrEnum):
    MANUFACTURER = "MANUFACTURER"
    BRAND_OWNER = "BRAND_OWNER"
    IMPORTER = "IMPORTER"
    DISTRIBUTOR = "DISTRIBUTOR"
    WHOLESALER = "WHOLESALER"
    RETAILER = "RETAILER"
    ECOMMERCE = "ECOMMERCE"
    DEALER = "DEALER"
    RENTAL = "RENTAL"
    OEM = "OEM"
    ODM = "ODM"
    SERVICE_PROVIDER = "SERVICE_PROVIDER"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class CompanyStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class ResearchStatus(StrEnum):
    NEW = "NEW"
    DISCOVERED = "DISCOVERED"
    COMPANY_RESEARCHED = "COMPANY_RESEARCHED"
    PRODUCT_RESEARCHED = "PRODUCT_RESEARCHED"
    CONTACT_RESEARCHED = "CONTACT_RESEARCHED"
    CONTACT_VERIFIED = "CONTACT_VERIFIED"
    SOCIAL_RESEARCHED = "SOCIAL_RESEARCHED"
    WHATSAPP_RESEARCHED = "WHATSAPP_RESEARCHED"
    FULLY_ENRICHED = "FULLY_ENRICHED"
    NEEDS_RESEARCH = "NEEDS_RESEARCH"
    RESEARCH_FAILED = "RESEARCH_FAILED"


class ResearchLevel(StrEnum):
    L0 = "L0"
    L1 = "L1"
    L2 = "L2"
    L3 = "L3"
    L4 = "L4"
    L5 = "L5"
    L6 = "L6"
    L7 = "L7"
    L8 = "L8"


class ContactStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    LEFT_COMPANY = "LEFT_COMPANY"
    UNKNOWN = "UNKNOWN"


class RoleType(StrEnum):
    OWNER = "OWNER"
    FOUNDER = "FOUNDER"
    CEO = "CEO"
    GENERAL_MANAGER = "GENERAL_MANAGER"
    PURCHASING_MANAGER = "PURCHASING_MANAGER"
    BUYER = "BUYER"
    PROCUREMENT = "PROCUREMENT"
    PRODUCT_MANAGER = "PRODUCT_MANAGER"
    IMPORT_MANAGER = "IMPORT_MANAGER"
    SALES_DIRECTOR = "SALES_DIRECTOR"
    MARKETING_DIRECTOR = "MARKETING_DIRECTOR"
    EXECUTIVE = "EXECUTIVE"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class PurchasingRole(StrEnum):
    DECISION_MAKER = "DECISION_MAKER"
    BUYER = "BUYER"
    INFLUENCER = "INFLUENCER"
    TECHNICAL = "TECHNICAL"
    EXECUTIVE = "EXECUTIVE"
    SALES = "SALES"
    MARKETING = "MARKETING"
    UNKNOWN = "UNKNOWN"


class Seniority(StrEnum):
    EXECUTIVE = "EXECUTIVE"
    SENIOR = "SENIOR"
    MID = "MID"
    JUNIOR = "JUNIOR"
    UNKNOWN = "UNKNOWN"


class DecisionPower(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNKNOWN = "UNKNOWN"


class MethodType(StrEnum):
    EMAIL = "EMAIL"
    PHONE = "PHONE"
    MOBILE = "MOBILE"
    WHATSAPP = "WHATSAPP"
    TELEGRAM = "TELEGRAM"
    SKYPE = "SKYPE"
    OTHER = "OTHER"


class VerificationStatus(StrEnum):
    UNVERIFIED = "UNVERIFIED"
    VERIFIED = "VERIFIED"
    INFERRED = "INFERRED"
    CONFLICTING = "CONFLICTING"


class PrivacyLabel(StrEnum):
    PUBLIC = "PUBLIC"
    PRIVATE = "PRIVATE"
    UNKNOWN = "UNKNOWN"


class BusinessOrPersonal(StrEnum):
    BUSINESS = "BUSINESS"
    PERSONAL = "PERSONAL"
    UNKNOWN = "UNKNOWN"


class Platform(StrEnum):
    LINKEDIN = "LINKEDIN"
    INSTAGRAM = "INSTAGRAM"
    FACEBOOK = "FACEBOOK"
    YOUTUBE = "YOUTUBE"
    TIKTOK = "TIKTOK"
    PINTEREST = "PINTEREST"
    X = "X"
    WHATSAPP = "WHATSAPP"
    TELEGRAM = "TELEGRAM"
    OTHER = "OTHER"


class ActivityLevel(StrEnum):
    VERY_HIGH = "VERY_HIGH"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    NONE = "NONE"
    UNKNOWN = "UNKNOWN"


class ProductCategory(StrEnum):
    RIB_BOAT = "RIB_BOAT"
    INFLATABLE_BOAT = "INFLATABLE_BOAT"
    SUP = "SUP"
    INFLATABLE_SUP = "INFLATABLE_SUP"
    HARD_SUP = "HARD_SUP"
    TOURING_SUP = "TOURING_SUP"
    ALL_ROUND_SUP = "ALL_ROUND_SUP"
    RACE_SUP = "RACE_SUP"
    YOGA_SUP = "YOGA_SUP"
    KAYAK = "KAYAK"
    INFLATABLE_KAYAK = "INFLATABLE_KAYAK"
    FISHING_KAYAK = "FISHING_KAYAK"
    TOURING_KAYAK = "TOURING_KAYAK"
    RIB = "RIB"
    PADDLE = "PADDLE"
    PUMP = "PUMP"
    LIFE_JACKET = "LIFE_JACKET"
    WATER_TOY = "WATER_TOY"
    ACCESSORY = "ACCESSORY"
    OTHER = "OTHER"


class BrandRelationship(StrEnum):
    OWNED = "OWNED"
    DISTRIBUTOR = "DISTRIBUTOR"
    IMPORTER = "IMPORTER"
    DEALER = "DEALER"
    RESELLER = "RESELLER"
    COMPETITOR = "COMPETITOR"
    PARTNER = "PARTNER"
    OTHER = "OTHER"


class EventType(StrEnum):
    NEW_PRODUCT = "NEW_PRODUCT"
    NEW_BRAND = "NEW_BRAND"
    NEW_DISTRIBUTOR = "NEW_DISTRIBUTOR"
    NEW_HIRING = "NEW_HIRING"
    NEW_MANAGER = "NEW_MANAGER"
    NEW_STORE = "NEW_STORE"
    EXPANSION = "EXPANSION"
    NEW_WAREHOUSE = "NEW_WAREHOUSE"
    TRADE_SHOW = "TRADE_SHOW"
    CATALOG_RELEASE = "CATALOG_RELEASE"
    WEBSITE_UPDATE = "WEBSITE_UPDATE"
    PARTNERSHIP = "PARTNERSHIP"
    PRODUCT_CATEGORY_EXPANSION = "PRODUCT_CATEGORY_EXPANSION"
    OTHER = "OTHER"


class TaskType(StrEnum):
    COMPANY_DISCOVERY = "COMPANY_DISCOVERY"
    COMPANY_RESEARCH = "COMPANY_RESEARCH"
    PRODUCT_RESEARCH = "PRODUCT_RESEARCH"
    BRAND_RESEARCH = "BRAND_RESEARCH"
    CONTACT_DISCOVERY = "CONTACT_DISCOVERY"
    EMAIL_DISCOVERY = "EMAIL_DISCOVERY"
    PHONE_DISCOVERY = "PHONE_DISCOVERY"
    WHATSAPP_DISCOVERY = "WHATSAPP_DISCOVERY"
    SOCIAL_DISCOVERY = "SOCIAL_DISCOVERY"
    VERIFICATION = "VERIFICATION"
    BUYING_SIGNAL_RESEARCH = "BUYING_SIGNAL_RESEARCH"
    LEAD_SCORING = "LEAD_SCORING"
    FULL_ENRICHMENT = "FULL_ENRICHMENT"


class TaskStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    RETRY = "RETRY"
    CANCELLED = "CANCELLED"


class SourceType(StrEnum):
    OFFICIAL_WEBSITE = "OFFICIAL_WEBSITE"
    OFFICIAL_CONTACT_PAGE = "OFFICIAL_CONTACT_PAGE"
    OFFICIAL_TEAM_PAGE = "OFFICIAL_TEAM_PAGE"
    OFFICIAL_PRODUCT_PAGE = "OFFICIAL_PRODUCT_PAGE"
    OFFICIAL_CATALOG = "OFFICIAL_CATALOG"
    OFFICIAL_SOCIAL = "OFFICIAL_SOCIAL"
    LINKEDIN = "LINKEDIN"
    INDUSTRY_DIRECTORY = "INDUSTRY_DIRECTORY"
    TRADE_PUBLICATION = "TRADE_PUBLICATION"
    SEARCH_RESULT = "SEARCH_RESULT"
    IMPORTED_DATA = "IMPORTED_DATA"
    OTHER = "OTHER"


class EvidenceConfidence(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNKNOWN = "UNKNOWN"


class Importance(StrEnum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class KnowledgeState(StrEnum):
    """AI must use KNOWN / UNKNOWN / INFERRED / CONFLICTING for important fields."""

    KNOWN = "KNOWN"
    UNKNOWN = "UNKNOWN"
    INFERRED = "INFERRED"
    CONFLICTING = "CONFLICTING"
